/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, NewsMedia as PrismaNewsMedia } from "@prisma/client";

export class NewsMediaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.NewsMediaCountArgs, "select">
  ): Promise<number> {
    return this.prisma.newsMedia.count(args);
  }

  async newsMedias(
    args: Prisma.NewsMediaFindManyArgs
  ): Promise<PrismaNewsMedia[]> {
    return this.prisma.newsMedia.findMany(args);
  }
  async newsMedia(
    args: Prisma.NewsMediaFindUniqueArgs
  ): Promise<PrismaNewsMedia | null> {
    return this.prisma.newsMedia.findUnique(args);
  }
  async createNewsMedia(
    args: Prisma.NewsMediaCreateArgs
  ): Promise<PrismaNewsMedia> {
    return this.prisma.newsMedia.create(args);
  }
  async updateNewsMedia(
    args: Prisma.NewsMediaUpdateArgs
  ): Promise<PrismaNewsMedia> {
    return this.prisma.newsMedia.update(args);
  }
  async deleteNewsMedia(
    args: Prisma.NewsMediaDeleteArgs
  ): Promise<PrismaNewsMedia> {
    return this.prisma.newsMedia.delete(args);
  }
}
