/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { NewsMedia } from "./NewsMedia";
import { NewsMediaCountArgs } from "./NewsMediaCountArgs";
import { NewsMediaFindManyArgs } from "./NewsMediaFindManyArgs";
import { NewsMediaFindUniqueArgs } from "./NewsMediaFindUniqueArgs";
import { CreateNewsMediaArgs } from "./CreateNewsMediaArgs";
import { UpdateNewsMediaArgs } from "./UpdateNewsMediaArgs";
import { DeleteNewsMediaArgs } from "./DeleteNewsMediaArgs";
import { NewsMediaService } from "../newsMedia.service";
@graphql.Resolver(() => NewsMedia)
export class NewsMediaResolverBase {
  constructor(protected readonly service: NewsMediaService) {}

  async _newsMediasMeta(
    @graphql.Args() args: NewsMediaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [NewsMedia])
  async newsMedias(
    @graphql.Args() args: NewsMediaFindManyArgs
  ): Promise<NewsMedia[]> {
    return this.service.newsMedias(args);
  }

  @graphql.Query(() => NewsMedia, { nullable: true })
  async newsMedia(
    @graphql.Args() args: NewsMediaFindUniqueArgs
  ): Promise<NewsMedia | null> {
    const result = await this.service.newsMedia(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NewsMedia)
  async createNewsMedia(
    @graphql.Args() args: CreateNewsMediaArgs
  ): Promise<NewsMedia> {
    return await this.service.createNewsMedia({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => NewsMedia)
  async updateNewsMedia(
    @graphql.Args() args: UpdateNewsMediaArgs
  ): Promise<NewsMedia | null> {
    try {
      return await this.service.updateNewsMedia({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => NewsMedia)
  async deleteNewsMedia(
    @graphql.Args() args: DeleteNewsMediaArgs
  ): Promise<NewsMedia | null> {
    try {
      return await this.service.deleteNewsMedia(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
