/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { NewsMediaService } from "../newsMedia.service";
import { NewsMediaCreateInput } from "./NewsMediaCreateInput";
import { NewsMedia } from "./NewsMedia";
import { NewsMediaFindManyArgs } from "./NewsMediaFindManyArgs";
import { NewsMediaWhereUniqueInput } from "./NewsMediaWhereUniqueInput";
import { NewsMediaUpdateInput } from "./NewsMediaUpdateInput";

export class NewsMediaControllerBase {
  constructor(protected readonly service: NewsMediaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: NewsMedia })
  async createNewsMedia(
    @common.Body() data: NewsMediaCreateInput
  ): Promise<NewsMedia> {
    return await this.service.createNewsMedia({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        typeField: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [NewsMedia] })
  @ApiNestedQuery(NewsMediaFindManyArgs)
  async newsMedias(@common.Req() request: Request): Promise<NewsMedia[]> {
    const args = plainToClass(NewsMediaFindManyArgs, request.query);
    return this.service.newsMedias({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        typeField: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: NewsMedia })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async newsMedia(
    @common.Param() params: NewsMediaWhereUniqueInput
  ): Promise<NewsMedia | null> {
    const result = await this.service.newsMedia({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        typeField: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: NewsMedia })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateNewsMedia(
    @common.Param() params: NewsMediaWhereUniqueInput,
    @common.Body() data: NewsMediaUpdateInput
  ): Promise<NewsMedia | null> {
    try {
      return await this.service.updateNewsMedia({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          typeField: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: NewsMedia })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteNewsMedia(
    @common.Param() params: NewsMediaWhereUniqueInput
  ): Promise<NewsMedia | null> {
    try {
      return await this.service.deleteNewsMedia({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          typeField: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
